baseURL = "https://heeyoung.netlify.com"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "twentytwenty"
title = "공간"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = "테스트 페이지"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "FORESRTRY는 상당히 편한 서비스입니다."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = true
title = "Contact us for more information."
[params.footer]
address = ""
content = "개인용 포트폴리오"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = ""
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "heeyoungkim@kakao.com"
facebook = ""
instagram = "https://www.instagram.com/kimheeyounghee"
linkedin = ""
twitter = ""
yelp = ""
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
